eval:
  path_to_checkpoints: "/adpt-test/checkpoints/YODAS/th/"  # NOTE: This is the path to the folder containing all the adapter checkpoints
  path_to_base_model: '/adpt-test/pretrained_models/whisper-large-v3-multilingual-50h/checkpoint-13616'
  path_to_test_data: "/adpt-test/data/MALT/th/test/"
  name_of_test_manifest: "test_manifest.json"
  name_of_output_file: "checkpoint-13412-th000-hr8"

  lang: "th" # Use ISO 639-1 convention 2 characters
  task: "transcribe"

  batch_size: 8
  checkpoint_chosen: '' # Leave empty to run all checkpoints