eval:
  path_to_checkpoints: "/adpt-test/checkpoints/MALT511/"  # NOTE: This is the path to the folder containing all the adapter checkpoints
  path_to_base_model: '/adpt-test/pretrained_models/whisper-large-v3-multilingual-50h/checkpoint-13616'
  path_to_test_data: "/adpt-test/data/MALT_5-1-1/hi/"
  name_of_test_manifest: "test_manifest.json"
  name_of_output_file: "MALT511_hi000_checkpoint-452"

  lang: "hi" # Use ISO 639-1 convention 2 characters
  task: "transcribe"

  batch_size: 16
  checkpoint_chosen: "checkpoint-452-hi" # Leave empty to run all checkpoints